# Deploy Terraform pipeline provision to deploy to AWS EKS
name: EKS Deploy

on: workflow_dispatch
env:
  # Verbosity setting for terraform log
  TF_LOG: INFO
  AWS_DEFAULT_REGION: us-east-1

defaults:
  run:
    working-directory: eks/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0

    - name: Add profile credentials to ~/.aws/credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.YOUR_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.YOUR_SECRET_ACCESS_KEY }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform init
      run: |
        cat ~/.aws/credentials
        ls
        terraform init
      
