# Deploy Terraform pipeline provision to deploy to AWS EKS
name: EKS Deploy

on: workflow_dispatch
env:
  # Verbosity setting for terraform log
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0

    - name: Configure AWS Credentials
  # You may pin to the exact commit or the version.
  # uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      uses: aws-actions/configure-aws-credentials@v4
      with:
      # AWS Region, e.g. us-east-2
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
      # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # AWS Secret Access Key. Required if aws-access-key-id is provided.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform init
      run: |
        cd eks/
        terraform init
      
