# Deploy Terraform pipeline provision to deploy to AWS EKS
name: EKS Deploy

on: workflow_dispatch
env:
  # Verbosity setting for terraform log
  TF_LOG: INFO
  AWS_DEFAULT_REGION: us-east-1

defaults:
  run:
    working-directory: eks/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0

    - name: Configure AWS Credentials Action for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4
      with:
          # AWS Region, e.g. us-east-2
          aws-region: us-east-1
          # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          # AWS Secret Access Key. Required if aws-access-key-id is provided.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Test configuration of AWS CLI
      run: |
        aws --version
        aws configure list

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform init
      run: |
        ls
        terraform init
      
